# Generated by Django 5.2.4 on 2025-07-15 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language1', models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('it', 'Italian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('pl', 'Polish'), ('ro', 'Romanian'), ('cs', 'Czech'), ('nl', 'Dutch'), ('sv', 'Swedish'), ('fi', 'Finnish'), ('no', 'Norwegian'), ('da', 'Danish'), ('el', 'Greek'), ('he', 'Hebrew'), ('th', 'Thai'), ('id', 'Indonesian'), ('fa', 'Persian'), ('hu', 'Hungarian'), ('sr', 'Serbian'), ('sk', 'Slovak'), ('hr', 'Croatian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('et', 'Estonian'), ('sl', 'Slovenian'), ('bg', 'Bulgarian'), ('ms', 'Malay'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('ur', 'Urdu'), ('am', 'Amharic'), ('zu', 'Zulu')], max_length=50)),
                ('language2', models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('it', 'Italian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('pl', 'Polish'), ('ro', 'Romanian'), ('cs', 'Czech'), ('nl', 'Dutch'), ('sv', 'Swedish'), ('fi', 'Finnish'), ('no', 'Norwegian'), ('da', 'Danish'), ('el', 'Greek'), ('he', 'Hebrew'), ('th', 'Thai'), ('id', 'Indonesian'), ('fa', 'Persian'), ('hu', 'Hungarian'), ('sr', 'Serbian'), ('sk', 'Slovak'), ('hr', 'Croatian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('et', 'Estonian'), ('sl', 'Slovenian'), ('bg', 'Bulgarian'), ('ms', 'Malay'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('ur', 'Urdu'), ('am', 'Amharic'), ('zu', 'Zulu')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.TextField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A1+', 'A1+'), ('A2', 'A2'), ('A2+', 'A2+'), ('B1', 'B1'), ('B1+', 'B1+'), ('B2', 'B2'), ('B2+', 'B2+'), ('C1', 'C1'), ('C1+', 'C1+')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='None', max_length=100)),
                ('translation', models.CharField(default='None', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pronunciation', models.CharField(blank=True, max_length=100, null=True)),
                ('example', models.TextField(blank=True, max_length=200, null=True)),
                ('part_of_speech', models.CharField(choices=[('n', 'Noun'), ('a', 'Adjective'), ('v', 'Verb'), ('pron', 'Pronoun'), ('ad', 'Adverb'), ('pr', 'Preposition'), ('co', 'Conjunction'), ('in', 'Interjection')], max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='dictionary.topic')),
            ],
        ),
    ]
