# Generated by Django 6.0.5 on 2026-07-19 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='dictionary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='dictionary.dictionary'),
            preserve_default=False,
        ),
    ]
